name: tests and linter check

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11'] # we want to test our package on several versions of Python

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: pip install --upgrade pip

      - name: Install dependencies  # make depends on poetry
        run: |
          pip install poetry
          make install

      - name: Pytest and linter project check
        run: |
          make lint
          make test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.1
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: 0d324884e3f9c1305fe74445a5e30058beb6440423bcc946fd091a5c24658bee
        with:
          coverageCommand: make test-coverage
          debug: true
